name: Stang Family Eyecare
favicon: null
layout_spectrum: 0.4005353320389986
typography_spectrum: 0.6557361758314073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9437542690429837
  lightness: 0.8278293285984546
  saturation: 0.8510698101017624
  rhythmicContrast: 0.8207866931334138
purpose: []
